spring:
  datasource:
    url: jdbc:mysql://djj-db.cjs2e2s6ov0a.ap-northeast-2.rds.amazonaws.com:3306/djj
    username: root
    password: capstone0!
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 695216799862-bvldqikpusajbrc5972l2oj0jqe3jlqe.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
              - openid
  jpa: #띄어쓰기 2칸
    database-platform: org.hibernate.dialect.MySQLDialect  # Dialect 명시적 설정
    hibernate: #띄어쓰기 4칸
      ddl-auto: update #띄어쓰기 6칸
    generate-ddl: true #띄어쓰기 4칸
    show-sql: true #띄어쓰기 4칸
    properties:
      hibernate:
        format_sql: true
